# Copyright (c) 2019 Mathieu-André Chiasson
# All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

git:
  quiet: true
  depth: 1

language: minimal

cache:
  timeout: 900
  directories: $HOME/.hunter

notifications:
  email: false

matrix:
  include:

    - os: linux
      dist: xenial
      compiler: clang
      env: DAWN_BUILD=linux-xenial-clang
      addons:
        apt:
          packages:
          - libgl1-mesa-dev
          - libvulkan-dev
          - mesa-common-dev
          - python2
          - python3
      script:
        - cmake -B.build -H. -DCMAKE_C_COMPILER=$(which clang) -DCMAKE_CXX_COMPILER=$(which clang++) -DCMAKE_PREFIX_PATH=$(pwd)/.install
        - cmake --build .build --target install -- -j$(grep -c ^processor /proc/cpuinfo)

    - os: linux
      dist: xenial
      compiler: gcc
      env: DAWN_BUILD=linux-xenial-gcc
      addons:
        apt:
          packages:
          - libgl1-mesa-dev
          - libvulkan-dev
          - mesa-common-dev
          - python2
          - python3
      script:
        - cmake -B.build -H. -DCMAKE_C_COMPILER=$(which clang) -DCMAKE_CXX_COMPILER=$(which clang++) -DCMAKE_PREFIX_PATH=$(pwd)/.install
        - cmake --build .build --target install -- -j$(grep -c ^processor /proc/cpuinfo)


