# Copyright (c) 2019 Mathieu-André Chiasson
# All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

git:
  quiet: true
  submodules: true
  depth: 1

language: minimal

cache:
  timeout: 900
  directories: 
    - $HOME/.hunter
    - $HOME/.linuxbrew

notifications:
  email: false

matrix:
  include:

#    - os: linux
#      dist: bionic
#      compiler: clang
#      env: DAWN_BUILD=linux-bionic-clang
#      addons:
#        apt:
#          packages:
#          - libgl1-mesa-dev
#          - libvulkan-dev
#          - mesa-common-dev
#          - python2.7
#          - python3
#      before_install:
#        - test -f $HOME/.linuxbrew/bin/brew || git clone https://github.com/Homebrew/brew.git $HOME/.linuxbrew
#        - PATH="$HOME/.linuxbrew/bin:$PATH"
#        - echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.bash_profile
#        - export MANPATH="$(brew --prefix)/share/man:$MANPATH"
#        - export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
#        - brew update
#      install:
#        - brew install cmake
#        - brew cleanup
#      before_script:
#        - cmake -B.build -H. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=$(which clang) -DCMAKE_CXX_COMPILER=$(which clang++) -DCMAKE_PREFIX_PATH=$(pwd)/.install
#      script:
#        - cmake --build .build --target install -- -j$(grep -c ^processor /proc/cpuinfo)

    - os: linux
      dist: bionic
      compiler: gcc
      env: DAWN_BUILD=linux-bionic-gcc
      addons:
        apt:
          packages:
          - libgl1-mesa-dev
          - libvulkan-dev
          - mesa-common-dev
          - python2.7
          - python3
      before_install:
        - test -f $HOME/.linuxbrew/bin/brew || git clone https://github.com/Homebrew/brew.git $HOME/.linuxbrew
        - PATH="$HOME/.linuxbrew/bin:$PATH"
        - echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.bash_profile
        - export MANPATH="$(brew --prefix)/share/man:$MANPATH"
        - export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
        - brew update
      install:
        - brew install cmake
        - brew cleanup
      before_script:
        - cmake -B.build -H. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=$(which gcc) -DCMAKE_CXX_COMPILER=$(which g++) -DCMAKE_PREFIX_PATH=$(pwd)/.install
      script:
        - cmake --build .build --target install -- -j$(grep -c ^processor /proc/cpuinfo)

    - os: windows
      language: cpp
      env: 
        - PATH=/c/Python37:/c/Python37/Scripts:/c/Python27:$PATH
      install: 
        - choco install cmake python python2
      before_script:
        - cmake -G "Visual Studio 15 2017" -A x64 -B.build -H. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$(pwd)/.install
      script:
        - cmake --build .build --target install
      cache:
        directories:
          - $HOME/.hunter
